//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_Accepted
    {
        public int id { get; set; }
        public string User_id { get; set; }
        public string User_name { get; set; }
        public Nullable<bool> Accepted_Studient { get; set; }
        public Nullable<bool> Accepted_Acountant { get; set; }
        public Nullable<int> charge { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
