//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Class
    {
        public int Id { get; set; }
        public Nullable<int> Class_id { get; set; }
        public string User_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Class Class { get; set; }
    }
}
