//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_payments
    {
        public int id { get; set; }
        public string User_id { get; set; }
        public string User_name { get; set; }
        public Nullable<double> payment { get; set; }
        public string description { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
